package dev.fabricmultiloader.testing;

import dev.fabricmultiloader.format.OmniFormat;
import dev.fabricmultiloader.format.manifest.ContainerManifest;
import dev.fabricmultiloader.format.manifest.FabricModJsonWriter;
import dev.fabricmultiloader.format.manifest.PayloadDescriptor;
import dev.fabricmultiloader.format.manifest.PayloadManifestWriter;

/**
 * Builds one payload jar: the mod Fabric actually selects.
 *
 * <p>Its {@code fabric.mod.json} is generated by {@link FabricModJsonWriter} rather than written by
 * hand, which is the point. The load-bearing assumption is about how the solver treats <em>these</em>
 * files, so a fixture whose metadata was hand-tuned would test a file the build never produces. The
 * conformance harness feeds real loaders exactly what the assembler would.
 */
public final class PayloadJarBuilder {

    private final ContainerManifest manifest;
    private final PayloadDescriptor payload;
    private final JarWriter jar = new JarWriter();

    /**
     * @param manifest the container manifest the payload belongs to
     * @param payload the payload to build
     */
    public PayloadJarBuilder(ContainerManifest manifest, PayloadDescriptor payload) {
        this.manifest = manifest;
        this.payload = payload;
        jar.entry("fabric.mod.json", FabricModJsonWriter.payload(manifest, payload));
        jar.entry(OmniFormat.PAYLOAD_DESCRIPTOR_PATH,
                PayloadManifestWriter.write(manifest, payload));
    }

    /** Adds an arbitrary entry, e.g. a mixin config or a resource. */
    public PayloadJarBuilder entry(String path, String content) {
        jar.entry(path, content);
        return this;
    }

    /** Replaces the generated {@code fabric.mod.json}, for testing a corrupted payload. */
    public PayloadJarBuilder overrideModJson(String content) {
        jar.entry("fabric.mod.json", content);
        return this;
    }

    /** Replaces the generated payload descriptor, for testing a divergence ({@code OMNI-2011}). */
    public PayloadJarBuilder overrideDescriptor(String content) {
        jar.entry(OmniFormat.PAYLOAD_DESCRIPTOR_PATH, content);
        return this;
    }

    /** The payload this builds. */
    public PayloadDescriptor payload() {
        return payload;
    }

    /** The container manifest it belongs to. */
    public ContainerManifest manifest() {
        return manifest;
    }

    /** The jar as bytes. */
    public byte[] toBytes() {
        return jar.toBytes();
    }

    /** Writes the jar to a file. */
    public java.nio.file.Path writeTo(java.nio.file.Path file) {
        return jar.writeTo(file);
    }
}
