package dev.fabricmultiloader.runtime.diag;

import dev.fabricmultiloader.format.OmniFormat;
import dev.fabricmultiloader.format.manifest.ContainerManifest;
import dev.fabricmultiloader.format.manifest.PayloadDescriptor;
import dev.fabricmultiloader.format.payload.Environment;
import dev.fabricmultiloader.format.payload.MatchResult;
import dev.fabricmultiloader.format.payload.Rejection;
import dev.fabricmultiloader.format.payload.ResolutionReport;
import dev.fabricmultiloader.runtime.RuntimeInfo;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Builds the full diagnostic text written to disk.
 *
 * <p>Longer than the message shown on screen, and deliberately so: the on-screen report answers
 * "what do I do now", while this one answers "what was actually going on", which is what a
 * maintainer needs when the reporter is not available to ask. It lists every loaded mod, every
 * payload with every constraint evaluated, and the active system properties — so a support case can
 * be settled from one attachment rather than three rounds of questions.
 */
public final class DiagnosticReport {

    /** Prefix of the system properties that influence the runtime. */
    private static final String PROPERTY_PREFIX = "fabricmultiloader.";

    private static final String RULE =
            "--------------------------------------------------------------------------------";

    /** The file name for the report of a failed launch. */
    public static String failureFileName(String containerModId) {
        return containerModId + "-diagnostic.txt";
    }

    /** The file name for the record of a successful launch. */
    public static String lastLaunchFileName(String containerModId) {
        return containerModId + "-last-launch.txt";
    }

    /**
     * Renders the full report.
     *
     * @param manifest the container manifest
     * @param environment the detected environment
     * @param resolution the resolution outcome
     * @param headline the short message shown on screen, or {@code null} on success
     * @return the report text
     */
    public static String render(ContainerManifest manifest, Environment environment,
            ResolutionReport resolution, String headline) {
        StringBuilder out = new StringBuilder(4096);

        out.append("FabricMultiLoader diagnostic report\n").append(RULE).append('\n');
        out.append("container      ").append(manifest.container().modId())
                .append(' ').append(manifest.container().modVersion()).append('\n');
        out.append("format         ").append(manifest.formatId())
                .append(" (schema ").append(manifest.schemaVersion()).append(")\n");
        out.append("runtime        ").append(RuntimeInfo.MOD_ID).append('\n');
        out.append("generated by   ").append(manifest.generator().tool())
                .append(' ').append(manifest.generator().version()).append('\n');
        out.append("outcome        ").append(outcome(resolution)).append('\n');
        out.append('\n');

        if (headline != null) {
            out.append("Message shown to the user\n").append(RULE).append('\n');
            out.append(headline);
            if (!headline.endsWith("\n")) {
                out.append('\n');
            }
            out.append('\n');
        }

        out.append("Environment\n").append(RULE).append('\n');
        out.append("minecraft      ").append(environment.minecraft()).append('\n');
        out.append("fabric loader  ").append(environment.fabricLoader()).append('\n');
        out.append("fabric api     ").append(environment.fabricApi().isUnknown()
                ? "not installed" : environment.fabricApi()).append('\n');
        out.append("java           ").append(environment.javaMajor())
                .append("  (class file major ")
                .append(environment.javaMajor() + 44).append(")\n");
        out.append("side           ").append(environment.side().id()).append('\n');
        out.append("development    ").append(environment.isDevelopment()).append('\n');
        out.append('\n');

        out.append("Payloads\n").append(RULE).append('\n');
        for (MatchResult result : resolution.results()) {
            PayloadDescriptor payload = result.payload();
            out.append(result.isMatch() ? "[active]   " : "[rejected] ")
                    .append(payload.id())
                    .append("  ").append(payload.modId())
                    .append(' ').append(payload.modVersion()).append('\n');
            out.append("           minecraft   ").append(payload.requires().minecraft()).append('\n');
            out.append("           java        ").append(payload.requires().java()).append('\n');
            out.append("           side        ").append(payload.requires().environment().id())
                    .append('\n');
            out.append("           class file  ").append(payload.classfileMajor()).append('\n');
            out.append("           mappings    ").append(payload.mappings()).append('\n');
            if (!payload.capabilities().isEmpty()) {
                out.append("           capabilities ").append(payload.capabilities()).append('\n');
            }
            for (Rejection rejection : result.rejections()) {
                out.append("           REJECTED    ").append(rejection.describe()).append('\n');
            }
            out.append('\n');
        }

        out.append("Loaded mods (").append(environment.loadedMods().size()).append(")\n")
                .append(RULE).append('\n');
        List<String> modIds = new ArrayList<String>(environment.loadedMods().keySet());
        Collections.sort(modIds);
        for (String modId : modIds) {
            out.append("  ").append(pad(modId, 40)).append(environment.loadedMods().get(modId))
                    .append('\n');
        }
        out.append('\n');

        out.append("FabricMultiLoader system properties\n").append(RULE).append('\n');
        boolean anyProperty = false;
        for (Map.Entry<Object, Object> property : System.getProperties().entrySet()) {
            String key = String.valueOf(property.getKey());
            if (key.startsWith(PROPERTY_PREFIX)) {
                out.append("  ").append(pad(key, 40)).append(property.getValue()).append('\n');
                anyProperty = true;
            }
        }
        if (!anyProperty) {
            out.append("  (none set — all defaults)\n");
        }
        out.append('\n');

        ContainerManifest.DiagnosticsInfo links = manifest.diagnostics();
        if (!links.isEmpty()) {
            out.append("Where to get help\n").append(RULE).append('\n');
            appendLink(out, "support", links.supportUrl());
            appendLink(out, "documentation", links.documentationUrl());
            appendLink(out, "download", links.downloadUrl());
            appendLink(out, "contact", links.contactLabel());
            out.append('\n');
        }

        out.append("Format reference: ").append(OmniFormat.FORMAT_ID).append('\n');
        return out.toString();
    }

    /** A one-line record of a successful launch, for support and modpack tooling. */
    public static String renderLastLaunch(ContainerManifest manifest, Environment environment,
            PayloadDescriptor active) {
        StringBuilder out = new StringBuilder(512);
        out.append("container   ").append(manifest.container().modId())
                .append(' ').append(manifest.container().modVersion()).append('\n');
        out.append("payload     ").append(active.id())
                .append("  (").append(active.modId()).append(' ')
                .append(active.modVersion()).append(")\n");
        out.append("minecraft   ").append(environment.minecraft()).append('\n');
        out.append("loader      ").append(environment.fabricLoader()).append('\n');
        out.append("fabric api  ").append(environment.fabricApi().isUnknown()
                ? "not installed" : environment.fabricApi()).append('\n');
        out.append("java        ").append(environment.javaMajor()).append('\n');
        out.append("side        ").append(environment.side().id()).append('\n');
        out.append("mappings    ").append(active.mappings()).append('\n');
        return out.toString();
    }

    private static String outcome(ResolutionReport resolution) {
        if (resolution.isResolved()) {
            return "resolved to payload '" + resolution.selected().id() + "'";
        }
        return resolution.isAmbiguous()
                ? "AMBIGUOUS — " + resolution.matches().size() + " payloads matched"
                : "UNRESOLVED — no payload matched";
    }

    private static void appendLink(StringBuilder out, String label, String value) {
        if (value != null && !value.isEmpty()) {
            out.append("  ").append(pad(label, 16)).append(value).append('\n');
        }
    }

    private static String pad(String value, int width) {
        if (value.length() >= width) {
            return value + " ";
        }
        StringBuilder padded = new StringBuilder(width);
        padded.append(value);
        while (padded.length() < width) {
            padded.append(' ');
        }
        return padded.toString();
    }

    private DiagnosticReport() {
        throw new AssertionError("no instances");
    }
}
